site:
  title: "McGillivray LAB"
  description: "Personal blog about technology, programming, and more - Now with CDN!"
  author: "Donald McGillivray"
  url: "https://donaldmcgillivray.com"
  language: "en"
  
build:
  content_dir: "content"
  output_dir: "output"
  static_dir: "static"
  templates_dir: "templates"
  
blog:
  posts_per_page: 10
  date_format: "%B %d, %Y"
  excerpt_length: 150
  
features:
  syntax_highlighting: true
  table_of_contents: false
  search: true
  rss: true
  sitemap: true
  
analytics:
  google_analytics_id: ""  # Add your GA4 ID here
  
social:
  twitter: ""
  github: ""
  linkedin: ""